### ISSUE TITLE
Broken links in the README file

### ISSUE THREAD

**Issue by OlliV** [cchen156/Learning-to-See-in-the-Dark#106]
Some important links in the README file are broken, for example a link to the paper shows 404. It seems particularly everything under `http://cchen156.web.engr.illinois.edu/` is broken.

**Comment by edchepen** [comment]
It looks like the README was updated. I found this link there:

https://cchen156.github.io <https://cchen156.github.io/>


From there there is a link to the See in the Dark (and other projects from the author). If you follow those links, I believe you will find the paper and other thigns that are missing from the old link

**Comment by cchen156** [comment]
Thanks! I have updated the link.
