### ISSUE TITLE
The trained model can't be downloaded

### ISSUE THREAD

**Issue by songl17** [cchen156/Learning-to-See-in-the-Dark#11]
The download_models.py always got a HTTP connection error, could you please provide a available download links? Thanks.

**Comment by cchen156** [comment]
Here they are:

https://drive.google.com/open?id=1wmx7AM6XWHjHIvpErmIouQgbQoMxAymG
https://drive.google.com/open?id=1OmrGMng1QuwUa8lf-_wBVvbRJwBr0ETr
https://drive.google.com/open?id=1PX5wA89d-JLmwQHqpBnyTYJxDVzC1gpt
https://drive.google.com/open?id=1VzyzQ9JglcxxqUe8yn3-cAeB1pJ4jxf4
