### ISSUE TITLE
The quantization

### ISSUE THREAD

**Issue by yueruchen** [cchen156/Learning-to-See-in-the-Dark#12]
Hi,

Thanks for your novel work. I have some questions. I noticed that you restrict the value of ground truth image around 0 to 1, then force the model to generate output image which is also around 0 to 1. I am confused that why not just use the original ground truth image as the label and produce the output image directly without multiplying 255. Is there any difference between these two ways? Could you please help answer this question?

Thanks,

**Comment by cchen156** [comment]
No, the input is [0,1] instead of the ground-truth, because there are some pixels with extreme large values (e.g., light source).

**Comment by yueruchen** [comment]
@cchen156 
Thanks for that. So setting the input around [0, 1] is to avoid gradient explosion? If not, will it produce the same result if I set the input around [0, 255]?

Thanks,

**Comment by cchen156** [comment]
I think you can set it to [0,255].
