### ISSUE TITLE
How can I test the model on my own dataset?

### ISSUE THREAD

**Issue by kuhung** [cchen156/Learning-to-See-in-the-Dark#2]
The model is nice, but how can I use the model to convert my own single jpg(or png) img ? Is there any Introduction?

**Comment by cchen156** [comment]
This model is not design for jpg or png files. The input is assumed to be the raw data by the camera, e.g., 14bit Bayer file by the Sony a7S II camera. If you use the 8bit jpg or png image as input, all the information is already lost and cannot be recovered. For example, if a low-light image looks nice after amplified by 300 times. The all the pixel values in the input will in in [0, 1] out of a [0, 255] scale. The information is already lost by quantization.

**Comment by kuhung** [comment]
I understand. Thank you.

**Comment by xuyifeng-nwpu** [comment]
How about 12 bit raw files captured by sony nex-6?
This raw file is not 14 bit.
Thanks!
