### ISSUE TITLE
Result of sony

### ISSUE THREAD

**Issue by AnukritiSingh1** [cchen156/Learning-to-See-in-the-Dark#20]
I downloaded the sony data of 22 GB, the training and testing programs were executed, the folder named 'result_sony' is created, with some files in it, but those files are not executable and there were no images to be seen, can you please tell me that was result was expected once the program is executed completely.

**Comment by cchen156** [comment]
You should see the PNG files. What did you get?

**Comment by AnukritiSingh1** [comment]
Please the check the screenshot in attachment, those are files formed under
'result_sony' folder.

**Comment by cchen156** [comment]
I did not see any attachment.

**Comment by cchen156** [comment]
Close issue because no response for more than a month.
