### ISSUE TITLE
iphone 6s weights

### ISSUE THREAD

**Issue by allendoss** [cchen156/Learning-to-See-in-the-Dark#38]
The official website contains a low light image and its result when run on SID model (http://web.engr.illinois.edu/~cchen156/SID/examples/6s.html). I could not find the weights for this in the repository. Is it possible to upload the weights for when trained on iPhone 6s?

**Comment by allendoss** [comment]
My bad, the paper mentions about cross-sensor generalization using Sony's camera sensor weights.

**Comment by allendoss** [comment]
Can you tell me how you've obtained the test files-Bayer data and RAW file using the iPhone 6s? I've tested with apps on iPhone and they all save it in DNG format. Also what files and formats should the input data be in?
I'm looking at testing this out and possibly generate a dataset for iPhone 6s to train on.

**Comment by allendoss** [comment]
Thanks for clearing. I just checked.

**Comment by mevinDhun** [comment]
@allendoss Have you been able to generate an iphone dataset?
