### ISSUE TITLE
Could you provide training test data set within 2G.

### ISSUE THREAD

**Issue by opticjian** [cchen156/Learning-to-See-in-the-Dark#4]
Hello,thank you for your help.Because my computer configuration is too low, RAM is only 4G, gpu memory 2G, although you provide  sonny(12G) data set, but still a bit big for me  and I can't download it .so could you provide training test data set within 2G. I just want to use a small amount of data to test the model.
Thank you !

**Comment by DomagojKorais** [comment]
I confirm with 2gb I Obtained OOB error. you need at least 4gb.

**Comment by opticjian** [comment]
@DomagojKorais  y

**Comment by opticjian** [comment]
@DomagojKorais  yes,I just test only one raw image (23M)and then shows that  my GPU out of  memorry.

**Comment by opticjian** [comment]
@cchen156   thank you ! I just test only one raw  sony image (23M)and then shows that my GPU out of memorry,if I don't use gpu for testing ,how much  cpu memory do I need at least to test a raw  sony image (23M)?

**Comment by cchen156** [comment]
Not sure. I never used CPU to test.
