### ISSUE TITLE
ratio multiplication

### ISSUE THREAD

**Issue by XhqGlorry11** [cchen156/Learning-to-See-in-the-Dark#40]
@kkruups @prabodhw96 @cchen156 Hi, congrats for your work. In your paper and code, during training, input and corresponding ground truth are first scaled between [0-1], and then input are scaled by ratio but the ground truth is still between [0-1]. Have you tried not to scale input by ratio and keep input and gt both in range [0-1] to train the network? Will it get better result and what's your opinion? THX!

**Comment by brouwa** [comment]
Even after being scaled by the ratio, the inputs are still in the range [0,1] (the saturated values are clipped).

Keep in mind that the input images originally are heavily underexposed, and must be amplified before being fed to the network. This is why they are multiplied by the ratio : so that the global exposure levels match between the ground truth and the input image.
The network is not technically in charge of amplifying the underexposed images. What it does is mainly demosaicking and denoising. Moreover, the network could not amplify the images on its own, since it hardly has any clue about the ratio it should apply.

**Comment by XhqGlorry11** [comment]
@brouwa Hi, thx for your reply and glad to discuss with you. During training process, we know the exposure difference between input and corresponding ground truth, so we can add a relative ratio to bright up the input. But during test process, I mean in real use case, we don't know the ratio because the ground truth is unknown. So we should solve the ratio selection problem both in training and test process.

**Comment by XhqGlorry11** [comment]
@brouwa Maybe we can scale the input and output by its maximum respectively. So that both input and output are exactly in range [0-1] and the maximum of input/output will exactly be 1. They are in the same range. And we can get rid of ratio. I haven't test this thoughts and I will do this later.

**Comment by brouwa** [comment]
That is one way to do it ! But it will give strange results for scenes which do not include any saturated nor black pixel. In this case the histograms would abusively be spread, yielding unnatural results.

**Comment by XhqGlorry11** [comment]
@brouwa Then any suggestions on how to solve the problem previously mentioned?

**Comment by allendoss** [comment]
@XhqGlorry11 So in order to test on a random image(during inference), we'd need the input image and its corresponding ground truth image?

**Comment by cchen156** [comment]
@XhqGlorry11 Hi, during the test time, we do not have the groundtruth. That is right. So we have to test a few ratios. This is like the ISO on the camera, when you find the image is too bright, you decrease the ISO. You cannot guess the proper ISO at one time before seeing any camera output. I think the camera auto ISO did the same thing: adjust the ISO based on the brightness of the output.

**Comment by XhqGlorry11** [comment]
@cchen156 Indeed! Have you ever thought about dealing with this problem, using some alternative ways to replace ratio multiplication....

**Comment by cchen156** [comment]
That is not my short-term plan.

**Comment by cchen156** [comment]
You can try to do that. I use the ratio based the groundtruth because we need to evaluate the PSNR.
