### ISSUE TITLE
Trained model (for iPhone)

### ISSUE THREAD

**Issue by nuthinking** [cchen156/Learning-to-See-in-the-Dark#5]
Amazing results, congrats!

Is it possible to download from somewhere the pre-trained model?

Thanks a lot!

**Comment by cchen156** [comment]
We test the iPhone image using the pre-trained Sony model.

**Comment by cchen156** [comment]
You can download it by running 
python download_dataset.py

You will need to revise test_Sony.py to test your own images. Since this model is not trained on the iPhone images, I do not expect that it works for every iPhone image.

**Comment by microbians** [comment]
Impressive project, congratulations! Looks like google is blocking the download because too much traffic. Maybe is a good idea to use torrent or something like that :)

**Comment by cchen156** [comment]
@microbians Thanks for mentioning this problem. We provide two additional links for the Sony and Fuji sets now. Please try:

https://drive.google.com/open?id=1G6VruemZtpOyHjOC5N8Ww3ftVXOydSXx
https://drive.google.com/open?id=1C7GeZ3Y23k1B8reRL79SqnZbRBc4uizH

**Comment by xiangcong** [comment]
how many iphone images have you tried?  And  about how many percent the model bought a good result? thanks?

**Comment by xiangcong** [comment]
I tried a picture captured in dark environment (just use default ISO, aperture and exposure) using iphone 6s. The results were not good(I have tried several different ratio). Does it because the parameters matter? or maybe it was not so dark? or maybe because the sensor is not the same type? thanks~
The data and result is in https://share.weiyun.com/57f31MV

**Comment by xiangcong** [comment]
Could you please provide the original dng file of the iphone6s picture, which you used in your paper? so that I can check if there's some mistake of my modified code, thx~

**Comment by xiangcong** [comment]
iphone 6s

**Comment by xiangcong** [comment]
there are some more results as below. https://share.weiyun.com/5TQyD6s on iphone 6s
parameters are the same as in the paper with IOS 400, exposure time 0.05s,  ratio 100.

**Comment by cchen156** [comment]
@xiangcong Did you test the black level and change the value in the code?

**Comment by shwanliu** [comment]
@cchen156 what did you mean black level ，how can I change the value in the code ？the value changed by ？？？

**Comment by shwanliu** [comment]
@cchen156 how can I test the black level???

**Comment by cchen156** [comment]
@shwanliu  Here it is: #7

**Comment by xiangcong** [comment]
@cchen156 After subtracting the correct black level, the results are much better for some cases. thanks!

**Comment by ghost0710** [comment]
@cchen156  Could you please provide modified code for subtract black level (dng format) ?
 and porvice dng data set  ?  I want train for dng format

**Comment by cchen156** [comment]
Hi, I do not have the dng data set. No groundtruth.

**Comment by mevinDhun** [comment]
@xiangcong Have you been able to make it with any iphone raw image? I get bad results on some images.

**Comment by xiangcong** [comment]
@mevinDhun Sorry~ I just tested with iphone 6s
