### ISSUE TITLE
Pnsr and SSIM

### ISSUE THREAD

**Issue by KeqiWangSXuniversity** [cchen156/Learning-to-See-in-the-Dark#52]
Hello,@cchen156,I used the cpkt file you provided to test PNSR and SSIM, but the measured value is still lower than the original text, PNSR=28.639, SSIM=0.7682, is it different from the method I used to test pnsr and ssim? Can you provide the method or code for testing pnsr and ssim?

**Comment by cchen156** [comment]
I save the results and test them in MATLAB with the default parameters.
