### ISSUE TITLE
axis of flip

### ISSUE THREAD

**Issue by r06922019** [cchen156/Learning-to-See-in-the-Dark#55]
Hi, 

According to this line,
https://github.com/cchen156/Learning-to-See-in-the-Dark/blob/master/train_Sony.py#L180
the flipping will occur at axis 0,
however for a batch of images, axis 0 is the 'batch' axis if understand your code correctly,
should it be axis=2 (left-right flip) instead?

**Comment by cchen156** [comment]
Revised.
