### ISSUE TITLE
how much GPU its need to run

### ISSUE THREAD

**Issue by amira133** [cchen156/Learning-to-See-in-the-Dark#64]
hello
I have a question: how much time its take with GPu or Cpu?(please add your GPU and CPU details)?

thanks

**Comment by Lelouch422** [comment]
There are GPU request in ReadMe: "Loading the raw data and proccesing by Rawpy takes significant more time than the backpropagation. By default, the code will load all the groundtruth data processed by Rawpy into memory without 8-bit or 16-bit quantization. This requires at least 64 GB RAM for training the Sony model and 128 GB RAM for the Fuji model. If you need to train it on a machine with less RAM, you may need to revise the code and use the groundtruth data on the disk. We provide the 16-bit groundtruth images processed by Rawpy: Sony (12 GB) and Fuji (22 GB)."

**Comment by amira133** [comment]
thanks...

**Comment by qiliux7** [comment]
@Lelouch422  What you mentioned is the memory requirements instead of the GPU memory requirements.
