### ISSUE TITLE
evaluation functioin

### ISSUE THREAD

**Issue by yutseng318** [cchen156/Learning-to-See-in-the-Dark#65]
hello,
I didn't find any evaluation code so I just calculate psnr and ssim by myself on your pre-trained model.
However, I got a much better ssim when I evaluate ssim on grayscale image of the output and gt. I guess it might not be the case that you do. 
So how did you evaluate your ssim? Do you use specific tool kit? 
I would be appreciate if you can provide me with your ssim implementation that you used to evaluate the result.

**Comment by cchen156** [comment]
I saved the results and evaluate them using MATLAB, on RGB images instead of grayscale images.

**Comment by yutseng318** [comment]
ok! Thanks
