### ISSUE TITLE
Mobile implementation for Tensorflow lite

### ISSUE THREAD

**Issue by mevinDhun** [cchen156/Learning-to-See-in-the-Dark#69]
Hi,
Google pixel phones make use of this project to run NightSight. Is it possible to port this project to make it on iphones by converting to tensorflow lite models? Or does it require too many resources to run that it can only be used on desktop systems?

**Comment by zhangjinhong17** [comment]
Hi mevinDhun,
    Where do you know Google pixel phones use this project?
    Google seems use different algorithm.

Thanks
Jinhong

**Comment by mevinDhun** [comment]
@zhangjinhong17 I read that NightSight was based on a neural network _see in the dark_, so i assumed it is based on the works from this paper. I might be wrong though. Do you know any similar implementation of low light enhancement neural network that is already available for mobile or can be ported to mobile?
