### ISSUE TITLE
Any hint for running on other camera raw (nikon,canon)

### ISSUE THREAD

**Issue by DomagojKorais** [cchen156/Learning-to-See-in-the-Dark#7]
Hi!
I was able to run the examples for Sony raw data and the results are amazing.
I would like to experiment with Canon and Nikon raws but with Canon's raws the model seems to never converge. I am able to run it but i don't get any output. I modified the test_Sony file changing the ARW extension in CR2 (Canon's raw). Any advice?

Thank you!

**Comment by cchen156** [comment]
Hi, we do not expect our pre-trained Sony mode can work for any camera sensors. Ideally, we will need data to train the models for other sensors. 

If you want to try the pre-trained Sony model on the Canon/Nikon raw data, you will need to change the data path, revise the file extension. You will also need to test the black level the data and change the numbers in the "pack_raw()" function. If Rawpy cannot read the black level from the file, you can test the black level by physically covering the lens (no light at all), but the data will not be all zeros.

**Comment by VVVVictorJ** [comment]
@DomagojKorais hello Do you get good result followed cchen156 mentioned the suggestion？
