### ISSUE TITLE
Is it possible to apply PNG images as inputs?

### ISSUE THREAD

**Issue by Qide** [cchen156/Learning-to-See-in-the-Dark#74]
Thanks for your great work! 
I tried to apply the pretrained model to enhance PNG format images, but outputs were weird. Is is caused by the model trained on RAW data? 
![image](https://user-images.githubusercontent.com/33931693/55058863-3d9df280-50a8-11e9-87df-73c7b076cdfd.png)
Is there a way to apply this network to normal images?

**Comment by zkeenly** [comment]
yes, you must use a raw image if you use the pre-trained model(different format need different train model) . in another way, you can train yourself dataset of png format. but in this paper, jpeg format is worse than the raw format dataset.
In my experiment, we translate the train dataset format from raw(sony raw) to adobe dng(a public raw format), the preferment also worse than paper, barely satisfactory.

**Comment by Qide** [comment]
> yes, you must use a raw image if you use the pre-trained model(different format need different train model) . in another way, you can train yourself dataset of png format. but in this paper, jpeg format is worse than the raw format dataset.
> In my experiment, we translate the train dataset format from raw(sony raw) to adobe dng(a public raw format), the preferment also worse than paper, barely satisfactory.

I'll think about it, thanks for your advice!
谢啦
