### ISSUE TITLE
Question about shutter settings

### ISSUE THREAD

**Issue by r06922019** [cchen156/Learning-to-See-in-the-Dark#79]
Hi, 

Thanks for your great work.
Since I didn't find any related information in the paper, I'd like to ask authors some questions about the Sony setting.

1. The Sony camera A7s2 supports silent shutter, or electronic shutter. 
Was the setting always on when the dataset is collected?
Or the setting was sometimes on? 
Or all images were captured with the mechanical shutter?

2. Have you tried to estimate the black level or always used the black level embedded in the file (512)

**Comment by cchen156** [comment]
1. It seems that I did not change the shutter and I am not sure what is the default one. 
2. I used the fixed 512.

**Comment by r06922019** [comment]
I see. Thanks for your reply.
