### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by nmstoker** [cchen156/Learning-to-See-in-the-Dark#8]
I noticed that the README suggests it needs Python 2.7 but from looking at the libraries, nothing jumps out that would be dependent on 2.7, so I'd have expected it to run with 3.

Is it simply that 2.7 is what you happened to develop / test with, or is there something in your code that specifically needs 2.7?

**Comment by cchen156** [comment]
You can try python 3. We just use python 2, but I think 3 should work without changing much of the code.

**Comment by jfjensen** [comment]
It works fine with Python 3.5. No change in the code necessary.
