### ISSUE TITLE
The “dataset” cannot be downloaded

### ISSUE THREAD

**Issue by brownliang** [cchen156/Learning-to-See-in-the-Dark#9]
Hi:
        I found I cannot download the dataset, could you pls give another URL?
https://docs.google.com/uc?export=download

Bad Request
Error 400

**Comment by cchen156** [comment]
Try these:

https://drive.google.com/open?id=1G6VruemZtpOyHjOC5N8Ww3ftVXOydSXx
https://drive.google.com/open?id=1C7GeZ3Y23k1B8reRL79SqnZbRBc4uizH

**Comment by brownliang** [comment]
Thanks very much. 
I have another question, the document of sony is 25G ， the download speed is so slowly. Is this document for training? or Just for test?

**Comment by brownliang** [comment]
Or do you have only test set that has smaller size? Just for checking the de-noise performance

**Comment by briantse100** [comment]
Thanks, @cchen156. I have the same question, download speed is slow. Could this be saved in other space like Baidu Cloud? Thanks!

**Comment by cchen156** [comment]
@brownliang You can download file parts in Baidu Drive: https://pan.baidu.com/s/1fk8EibhBe_M1qG0ax9LQZA#list/path=%2F
